// eslint-disable-next-line import/no-anonymous-default-export
export default {
    HEADER_REQUEST_AUTHORIZE: 'HEADER_REQUEST_AUTHORIZE',
    CLEAR_USER_STORE: 'CLEAR_USER_STORE',
    CLEAR_PRODUCT_STORE: 'CLEAR_PRODUCT_STORE',

    AUTH_ACTION_CLEAR_ERROR: 'AUTH_ACTION_CLEAR_ERROR',
    AUTH_ACTION_REGISTER: 'AUTH_ACTION_REGISTER',
    AUTH_ACTION_LOGIN: 'AUTH_ACTION_LOGIN',
    AUTH_ACTION_REQUEST: 'AUTH_ACTION_REQUEST',
    AUTH_ACTION_SUCCESS: 'AUTH_ACTION_SUCCESS',
    AUTH_ACTION_ERROR: 'AUTH_ACTION_ERROR',
    AUTH_ACTION_CLEAR: 'AUTH_ACTION_CLEAR',

    CREATE_PRODUCT_ACTION: 'CREATE_PRODUCT_ACTION',
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',

    GET_PRODUCT_ACTION: 'GET_PRODUCT_ACTION',
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_ERROR: 'GET_PRODUCT_ERROR',

    GET_USER_ACTION: 'GET_USER_ACTION',
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',

    GET_PRODUCTS_ACTION: 'GET_PRODUCTS_ACTION',
    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCT_BY_ID_ACTION: 'GET_PRODUCT_BY_ID_ACTION',
    GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',

    UPDATE_PRODUCT_ACTION: 'UPDATE_PRODUCT_ACTION',
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',
    UPDATE_STORE_AFTER_UPDATE_PRODUCT: 'UPDATE_STORE_AFTER_UPDATE_PRODUCT',
    CLEAR_UPDATE_PRODUCT_STORE: 'CLEAR_UPDATE_PRODUCT_STORE',

    DELETE_PRODUCT_ACTION: 'DELETE_PRODUCT_ACTION',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    PRODUCT_ERROR: 'PRODUCT_ERROR',
}