// eslint-disable-next-line import/no-anonymous-default-export
export default {
    CLEAR_USER_STORE: 'CLEAR_USER_STORE',

    AUTH_ACTION_CLEAR_ERROR: 'AUTH_ACTION_CLEAR_ERROR',
    AUTH_ACTION_REGISTER: 'AUTH_ACTION_REGISTER',
    AUTH_ACTION_REQUEST: 'AUTH_ACTION_REQUEST',
    AUTH_ACTION_SUCCESS: 'AUTH_ACTION_SUCCESS',
    AUTH_ACTION_ERROR: 'AUTH_ACTION_ERROR',
    AUTH_ACTION_CLEAR: 'AUTH_ACTION_CLEAR',

    USER_ERROR: 'USER_ERROR',
}